### ISSUE TITLE
VM's RAM should be increased

### ISSUE THREAD

**Issue by kaloyan-raev** [fread-ink/fread-vagrant#3]
The Vagrant VM is created with 384 MB of RAM. I noticed that this is quite low for compiling the toolchain. Most of the time is spend on swapping. I lost patience after about 80 mins and the process was still at the beginning - compiling gcc pass 1. After manually increasing the VM's memory to 2 GB the whole toolchain was compiled in just 68 mins.

I am opening this issue for others to know about this and save them many many hours of waiting.

There two ways to make an improvement:
- increase the RAM in the Vagrantfile configuration
- add a note to the README

@Juul which of the above do you prefer?

**Comment by Juul** [comment]
Ah! I didn't even notice that. Yeah I think increasing the RAM is a good idea. Maybe we should also add a note that it can be decreased to 384 MB but that it will take a lot longer (just in case someone doesn't have a lot of ram on their system).

**Comment by Juul** [comment]
Fixed by 035e78bd8fd23afdc3e0f4ec451db14bd244fc03
